name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - website/**
  pull_request:
    branches: [ * ]
    paths-ignore:
    - website/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
        package:
          - name: "http4py-core"
            path: "core"
          - name: "http4py-server-random"
            path: "server/random"

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --dev

    - name: Test ${{ matrix.package.name }}
      run: uv run --package ${{ matrix.package.name }} python -m pytest ${{ matrix.package.path }}/tests/ -v --tb=short

    - name: Type check ${{ matrix.package.name }}
      run: uv run --package ${{ matrix.package.name }} mypy ${{ matrix.package.path }}/src/

    - name: Run linting
      run: uv run ruff check .

    - name: Check formatting
      run: uv run ruff format --check .

  build:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --dev

    - name: Build all packages
      run: |
        uv build --package http4py-core
        uv build --package http4py-server-random

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          core/dist/
          server/random/dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    environment: release
    permissions:
      id-token: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
