name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - website/**
  pull_request:
    paths-ignore:
    - website/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --dev

    - name: Install yq
      run: sudo snap install yq

    - name: Run all checks
      run: ./scripts/http4py.sh check

